### ISSUE TITLE
为什么排行榜半个月都没更新？

### ISSUE THREAD

**Issue by yaleimeng** [CLUEbenchmark/SuperCLUELYB#3]
是因为收集到的模型比较数据太少吗？

SuperCLUE琅琊榜   [点击加入对战](https://www.superclueai.com/lyb)
我们使用Elo评级系统来计算模型的相对性能。我们将定期发布新的排行榜。如果你想看到更多的模型，请联系我们：CLUEbenchmark@163.com
最后一次更新: 2023-05-29 18:22:35
[[文章]](https://mp.weixin.qq.com/s/n7J5Tth2zmuOREtwugLbwg) [[GitHub]](https://github.com/CLUEbenchmark/SuperCLUElyb)

**Comment by brightmart** [comment]
会定期更新，考虑月度级别进行更新

**Comment by lidh15** [comment]
Claude怎么直接没了？是他们不允许调用了吗？
